#!/usr/bin/env bash
# script that transfers a file to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
path_to_file=$1
ip=$2
user_name=$3
path_to_ssh_key=$4

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$user_name@$ip:~/"

if [ $? -eq 0 ]
then
	echo "FILE TRANSFER COMPLETE"
else
	echo "FILE TRANSFER ERROR"
fi
