#!/usr/bin/env bash
#Bash script that creates the file "/var/run/myscript.pid" and handles signals.
echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command" ; rm -f /var/run/myscript.pid ; exit 0' SIGTERM
trap 'echo "Y U no love me?!" ; rm -f /var/run/myscript.pid ; exit 0' SIGINT
trap 'rm -f /var/run/myscript.pid ; exit 0' SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 1
done
