#!/usr/bin/env bash
#Bash script that manages "manage_my_process"
FILE="manage_my_process"
PID_FILE="/var/run/my_process.pid"

start_function() {
	if [ -e "$FILE" ]; then
		"$FILE" &
		echo $! > "$PID_FILE"
		echo "manage_my_process started"
	fi
}

stop_function() {
	if [ -e "$FILE" ]; then
		pid=$(cat "$PID_FILE")
		kill "$pid"
		rm "$PID_FILE"
		echo "manage_my_process stopped"
	fi
}

restart_function() {
	if [ -e "$FILE" ]; then
		stop_function
		start_function
		echo "manage_my_process restarted"
	fi
}

case "$1" in
	start)
		start_function
		;;
	stop)
		stop_function
		;;
	restart)
		restart_function
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
