#!/usr/bin/env bash
#Bash script that displays "Best School" 10 times.
list=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School")
for item in "${list[@]}"; do
	echo "$item"
done
